# Copyright (C) Internet Systems Consortium, Inc. ("ISC")
#
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, you can obtain one at https://mozilla.org/MPL/2.0/.
#
# See the COPYRIGHT file distributed with this work for additional
# information regarding copyright ownership.

# Header files used by gen.c to produce enumtype.h and rdatastruct.h.
dns_header_depfiles += files(
    'a6_38.h',
    'a_1.h',
    'aaaa_28.h',
    'afsdb_18.h',
    'amtrelay_260.h',
    'apl_42.h',
    'atma_34.h',
    'avc_258.h',
    'brid_68.h',
    'caa_257.h',
    'cdnskey_60.h',
    'cds_59.h',
    'cert_37.h',
    'cname_5.h',
    'csync_62.h',
    'dhcid_49.h',
    'dlv_32769.h',
    'dname_39.h',
    'dnskey_48.h',
    'doa_259.h',
    'ds_43.h',
    'dsync_66.h',
    'eid_31.h',
    'eui48_108.h',
    'eui64_109.h',
    'gpos_27.h',
    'hhit_67.h',
    'hinfo_13.h',
    'hip_55.h',
    'https_65.h',
    'ipseckey_45.h',
    'isdn_20.h',
    'key_25.h',
    'keydata_65533.h',
    'kx_36.h',
    'l32_105.h',
    'l64_106.h',
    'loc_29.h',
    'lp_107.h',
    'mb_7.h',
    'md_3.h',
    'mf_4.h',
    'mg_8.h',
    'minfo_14.h',
    'mr_9.h',
    'mx_15.h',
    'naptr_35.h',
    'nid_104.h',
    'nimloc_32.h',
    'ninfo_56.h',
    'ns_2.h',
    'nsap-ptr_23.h',
    'nsap_22.h',
    'nsec3_50.h',
    'nsec3param_51.h',
    'nsec_47.h',
    'null_10.h',
    'nxt_30.h',
    'openpgpkey_61.h',
    'opt_41.h',
    'ptr_12.h',
    'px_26.h',
    'rdatastructpre.h',
    'rdatastructsuf.h',
    'resinfo_261.h',
    'rkey_57.h',
    'rp_17.h',
    'rrsig_46.h',
    'rt_21.h',
    'sig_24.h',
    'sink_40.h',
    'smimea_53.h',
    'soa_6.h',
    'spf_99.h',
    'srv_33.h',
    'sshfp_44.h',
    'svcb_64.h',
    'ta_32768.h',
    'talink_58.h',
    'tkey_249.h',
    'tlsa_52.h',
    'tsig_250.h',
    'txt_16.h',
    'uri_256.h',
    'wallet_262.h',
    'wks_11.h',
    'x25_19.h',
    'zonemd_63.h',
)
