# Copyright (C) Internet Systems Consortium, Inc. ("ISC")
#
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, you can obtain one at https://mozilla.org/MPL/2.0/.
#
# See the COPYRIGHT file distributed with this work for additional
# information regarding copyright ownership.

probe_hdr = dtrace_header.process('probes-dns.d')
probe_src = [probe_hdr, files('xfrin.c')]

# dns_inc += include_directories('include')
dns_inc_p += include_directories('.')

dns_header_depfiles = []
subdir('rdata')

dns_gen_headers = []

dns_header_gen = executable(
    'gen',
    files('gen.c'),
    sources: default_sanitize_options,
    install: false,
    native: true,
)

subdir('include')

dns_srcset.add(dns_gen_headers)
dns_srcset.add(when: dnstap_dep, if_true: files('dnstap.c'))
dns_srcset.add(when: maxminddb_dep, if_true: files('geoip2.c'))
dns_srcset.add(when: [gssapi_dep, krb5_dep], if_true: files('gssapi_link.c'))

if config.get('HAVE_DTRACE')
    dns_probe_objects += static_library(
        'dns-probe-target',
        probe_src,
        build_by_default: false,
        dependencies: urcu_dep,
        implicit_include_directories: false,
        include_directories: [isc_inc, dns_inc, dns_inc_p],
        sources: dns_gen_headers,
    ).extract_all_objects(recursive: false)
endif

dns_srcset.add(
    when: 'HAVE_DTRACE',
    if_true: [
        custom_target(
            'dns-probe',
            input: [files('probes-dns.d'), dns_probe_objects],
            output: 'dns-probes.o',
            command: [
                dtrace,
                '-G',
                '-o', '@OUTPUT@',
                '-s', '@INPUT@',
            ],
        ),
        probe_hdr,
    ],
    if_false: probe_src,
)

dns_srcset.add(
    files(
        'rdata/any_255/tsig_250.c',
        'rdata/ch_3/a_1.c',
        'rdata/generic/afsdb_18.c',
        'rdata/generic/amtrelay_260.c',
        'rdata/generic/avc_258.c',
        'rdata/generic/brid_68.c',
        'rdata/generic/caa_257.c',
        'rdata/generic/cdnskey_60.c',
        'rdata/generic/cds_59.c',
        'rdata/generic/cert_37.c',
        'rdata/generic/cname_5.c',
        'rdata/generic/csync_62.c',
        'rdata/generic/dlv_32769.c',
        'rdata/generic/dname_39.c',
        'rdata/generic/dnskey_48.c',
        'rdata/generic/doa_259.c',
        'rdata/generic/ds_43.c',
        'rdata/generic/dsync_66.c',
        'rdata/generic/eui48_108.c',
        'rdata/generic/eui64_109.c',
        'rdata/generic/gpos_27.c',
        'rdata/generic/hhit_67.c',
        'rdata/generic/hinfo_13.c',
        'rdata/generic/hip_55.c',
        'rdata/generic/ipseckey_45.c',
        'rdata/generic/isdn_20.c',
        'rdata/generic/key_25.c',
        'rdata/generic/keydata_65533.c',
        'rdata/generic/l32_105.c',
        'rdata/generic/l64_106.c',
        'rdata/generic/loc_29.c',
        'rdata/generic/lp_107.c',
        'rdata/generic/mb_7.c',
        'rdata/generic/md_3.c',
        'rdata/generic/mf_4.c',
        'rdata/generic/mg_8.c',
        'rdata/generic/minfo_14.c',
        'rdata/generic/mr_9.c',
        'rdata/generic/mx_15.c',
        'rdata/generic/naptr_35.c',
        'rdata/generic/nid_104.c',
        'rdata/generic/ninfo_56.c',
        'rdata/generic/ns_2.c',
        'rdata/generic/nsec3_50.c',
        'rdata/generic/nsec3param_51.c',
        'rdata/generic/nsec_47.c',
        'rdata/generic/null_10.c',
        'rdata/generic/nxt_30.c',
        'rdata/generic/openpgpkey_61.c',
        'rdata/generic/opt_41.c',
        'rdata/generic/ptr_12.c',
        'rdata/generic/resinfo_261.c',
        'rdata/generic/rkey_57.c',
        'rdata/generic/rp_17.c',
        'rdata/generic/rrsig_46.c',
        'rdata/generic/rt_21.c',
        'rdata/generic/sig_24.c',
        'rdata/generic/sink_40.c',
        'rdata/generic/smimea_53.c',
        'rdata/generic/soa_6.c',
        'rdata/generic/spf_99.c',
        'rdata/generic/sshfp_44.c',
        'rdata/generic/ta_32768.c',
        'rdata/generic/talink_58.c',
        'rdata/generic/tkey_249.c',
        'rdata/generic/tlsa_52.c',
        'rdata/generic/txt_16.c',
        'rdata/generic/uri_256.c',
        'rdata/generic/wallet_262.c',
        'rdata/generic/x25_19.c',
        'rdata/generic/zonemd_63.c',
        'rdata/hs_4/a_1.c',
        'rdata/in_1/a6_38.c',
        'rdata/in_1/a_1.c',
        'rdata/in_1/aaaa_28.c',
        'rdata/in_1/apl_42.c',
        'rdata/in_1/atma_34.c',
        'rdata/in_1/dhcid_49.c',
        'rdata/in_1/eid_31.c',
        'rdata/in_1/https_65.c',
        'rdata/in_1/kx_36.c',
        'rdata/in_1/nimloc_32.c',
        'rdata/in_1/nsap-ptr_23.c',
        'rdata/in_1/nsap_22.c',
        'rdata/in_1/px_26.c',
        'rdata/in_1/srv_33.c',
        'rdata/in_1/svcb_64.c',
        'rdata/in_1/wks_11.c',
        'acl.c',
        'adb.c',
        'badcache.c',
        'byaddr.c',
        'cache.c',
        'callbacks.c',
        'catz.c',
        'client.c',
        'clientinfo.c',
        'compress.c',
        'db.c',
        'dbiterator.c',
        'deleg.c',
        'diff.c',
        'dispatch.c',
        'dlz.c',
        'dns64.c',
        'dnssec.c',
        'ds.c',
        'dst_api.c',
        'dst_parse.c',
        'dyndb.c',
        'ecs.c',
        'ede.c',
        'fixedname.c',
        'forward.c',
        'gssapictx.c',
        'hmac_link.c',
        'ipkeylist.c',
        'iptable.c',
        'journal.c',
        'kasp.c',
        'key.c',
        'keydata.c',
        'keymgr.c',
        'keystore.c',
        'keytable.c',
        'lib.c',
        'master.c',
        'masterdump.c',
        'message.c',
        'name.c',
        'nametree.c',
        'ncache.c',
        'notify.c',
        'nsec.c',
        'nsec3.c',
        'nta.c',
        'openssl_link.c',
        'opensslecdsa_link.c',
        'openssleddsa_link.c',
        'opensslrsa_link.c',
        'order.c',
        'peer.c',
        'private.c',
        'qp.c',
        'qpcache.c',
        'qpzone.c',
        'rcode.c',
        'rdata.c',
        'rdata_registry.c',
        'rdatalist.c',
        'rdataset.c',
        'rdatasetiter.c',
        'rdataslab.c',
        'rdatavec.c',
        'remote.c',
        'request.c',
        'resconf.c',
        'resolver.c',
        'result.c',
        'rootns.c',
        'rpz.c',
        'rriterator.c',
        'rrl.c',
        'sdlz.c',
        'skr.c',
        'soa.c',
        'ssu.c',
        'ssu_external.c',
        'stats.c',
        'time.c',
        'tkey.c',
        'transport.c',
        'tsig.c',
        'ttl.c',
        'unreachcache.c',
        'update.c',
        'validator.c',
        'view.c',
        'zone.c',
        'zonefetch.c',
        'zoneproperties.c',
        'zoneverify.c',
        'zt.c',
    ),
)
