# Copyright (C) Internet Systems Consortium, Inc. ("ISC")
#
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, you can obtain one at https://mozilla.org/MPL/2.0/.
#
# See the COPYRIGHT file distributed with this work for additional
# information regarding copyright ownership.

probe_hdr = dtrace_header.process('probes-dns.d')
probe_src = [probe_hdr, files('xfrin.c')]

# dns_inc += include_directories('include')
dns_inc_p += include_directories('.')

subdir('include')
dns_srcset.add(when: dnstap_dep, if_true: files('dnstap.c'))
dns_srcset.add(when: maxminddb_dep, if_true: files('geoip2.c'))
dns_srcset.add(when: [gssapi_dep, krb5_dep], if_true: files('gssapi_link.c'))

if config.get('HAVE_DTRACE')
    dns_probe_objects += static_library(
        'dns-probe-target',
        probe_src,
        build_by_default: false,
        dependencies: urcu_dep,
        implicit_include_directories: false,
        include_directories: [isc_inc, dns_inc, dns_inc_p],
    ).extract_all_objects(recursive: false)
endif

dns_srcset.add(
    when: 'HAVE_DTRACE',
    if_true: [
        custom_target(
            'dns-probe',
            input: [files('probes-dns.d'), dns_probe_objects],
            output: 'dns-probes.o',
            command: [
                dtrace,
                '-G',
                '-o', '@OUTPUT@',
                '-s', '@INPUT@',
            ],
        ),
        probe_hdr,
    ],
    if_false: probe_src,
)

dns_srcset.add(
    files(
        'rdata/a6_38.c',
        'rdata/a_1.c',
        'rdata/aaaa_28.c',
        'rdata/afsdb_18.c',
        'rdata/amtrelay_260.c',
        'rdata/apl_42.c',
        'rdata/atma_34.c',
        'rdata/avc_258.c',
        'rdata/brid_68.c',
        'rdata/caa_257.c',
        'rdata/cdnskey_60.c',
        'rdata/cds_59.c',
        'rdata/cert_37.c',
        'rdata/cname_5.c',
        'rdata/csync_62.c',
        'rdata/dhcid_49.c',
        'rdata/dlv_32769.c',
        'rdata/dname_39.c',
        'rdata/dnskey_48.c',
        'rdata/doa_259.c',
        'rdata/ds_43.c',
        'rdata/dsync_66.c',
        'rdata/eid_31.c',
        'rdata/eui48_108.c',
        'rdata/eui64_109.c',
        'rdata/gpos_27.c',
        'rdata/hhit_67.c',
        'rdata/hinfo_13.c',
        'rdata/hip_55.c',
        'rdata/https_65.c',
        'rdata/ipseckey_45.c',
        'rdata/isdn_20.c',
        'rdata/key_25.c',
        'rdata/keydata_65533.c',
        'rdata/kx_36.c',
        'rdata/l32_105.c',
        'rdata/l64_106.c',
        'rdata/loc_29.c',
        'rdata/lp_107.c',
        'rdata/mb_7.c',
        'rdata/md_3.c',
        'rdata/mf_4.c',
        'rdata/mg_8.c',
        'rdata/minfo_14.c',
        'rdata/mr_9.c',
        'rdata/mx_15.c',
        'rdata/naptr_35.c',
        'rdata/nid_104.c',
        'rdata/nimloc_32.c',
        'rdata/ninfo_56.c',
        'rdata/ns_2.c',
        'rdata/nsap-ptr_23.c',
        'rdata/nsap_22.c',
        'rdata/nsec3_50.c',
        'rdata/nsec3param_51.c',
        'rdata/nsec_47.c',
        'rdata/null_10.c',
        'rdata/nxt_30.c',
        'rdata/openpgpkey_61.c',
        'rdata/opt_41.c',
        'rdata/ptr_12.c',
        'rdata/px_26.c',
        'rdata/resinfo_261.c',
        'rdata/rkey_57.c',
        'rdata/rp_17.c',
        'rdata/rrsig_46.c',
        'rdata/rt_21.c',
        'rdata/sig_24.c',
        'rdata/sink_40.c',
        'rdata/smimea_53.c',
        'rdata/soa_6.c',
        'rdata/spf_99.c',
        'rdata/srv_33.c',
        'rdata/sshfp_44.c',
        'rdata/svcb_64.c',
        'rdata/ta_32768.c',
        'rdata/talink_58.c',
        'rdata/tkey_249.c',
        'rdata/tlsa_52.c',
        'rdata/tsig_250.c',
        'rdata/txt_16.c',
        'rdata/uri_256.c',
        'rdata/wallet_262.c',
        'rdata/wks_11.c',
        'rdata/x25_19.c',
        'rdata/zonemd_63.c',
        'acl.c',
        'adb.c',
        'badcache.c',
        'byaddr.c',
        'cache.c',
        'callbacks.c',
        'catz.c',
        'client.c',
        'clientinfo.c',
        'compress.c',
        'db.c',
        'dbiterator.c',
        'deleg.c',
        'diff.c',
        'dispatch.c',
        'dlz.c',
        'dns64.c',
        'dnssec.c',
        'ds.c',
        'dst_api.c',
        'dst_parse.c',
        'dyndb.c',
        'ecs.c',
        'ede.c',
        'fixedname.c',
        'forward.c',
        'gssapictx.c',
        'hmac_link.c',
        'ipkeylist.c',
        'iptable.c',
        'journal.c',
        'kasp.c',
        'key.c',
        'keydata.c',
        'keymgr.c',
        'keystore.c',
        'keytable.c',
        'lib.c',
        'master.c',
        'masterdump.c',
        'message.c',
        'name.c',
        'nametree.c',
        'ncache.c',
        'notify.c',
        'nsec.c',
        'nsec3.c',
        'nta.c',
        'openssl_link.c',
        'opensslecdsa_link.c',
        'openssleddsa_link.c',
        'opensslrsa_link.c',
        'order.c',
        'peer.c',
        'private.c',
        'qp.c',
        'qpcache.c',
        'qpzone.c',
        'rcode.c',
        'rdata.c',
        'rdata_registry.c',
        'rdatalist.c',
        'rdataset.c',
        'rdatasetiter.c',
        'rdataslab.c',
        'rdatavec.c',
        'remote.c',
        'request.c',
        'resconf.c',
        'resolver.c',
        'result.c',
        'rootns.c',
        'rpz.c',
        'rriterator.c',
        'rrl.c',
        'sdlz.c',
        'skr.c',
        'soa.c',
        'ssu.c',
        'ssu_external.c',
        'stats.c',
        'time.c',
        'tkey.c',
        'transport.c',
        'tsig.c',
        'ttl.c',
        'unreachcache.c',
        'update.c',
        'validator.c',
        'view.c',
        'zone.c',
        'zonefetch.c',
        'zoneproperties.c',
        'zoneverify.c',
        'zt.c',
    ),
)
