/*
 * Copyright (C) Internet Systems Consortium, Inc. ("ISC")
 *
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See the COPYRIGHT file distributed with this work for additional
 * information regarding copyright ownership.
 */

/*
 * Rdata type registry.
 *
 * Maps (rdclass, type) pairs to type descriptors containing method
 * tables and metadata.  The table is sorted by (type, rdclass) for
 * binary search.  Generic (class-independent) entries have rdclass=0
 * and serve as fallback when no class-specific entry exists.
 */

#include <stddef.h>
#include <string.h>

#include <isc/ascii.h>
#include <isc/util.h>

#include <dns/rdata.h>
#include <dns/rdataclass.h>
#include <dns/rdatatype.h>

#include "rdata_p.h"

/*
 * Type descriptor table, sorted by (type, rdclass).
 *
 * As types are converted from the old gen.c/#include system to the
 * vtable approach, their descriptors are added here (or this table
 * is generated by gen.c -r).
 */
static const dns_rdata_typedesc_t typedesc_table[] = {
	/* Placeholder — table is populated as types are converted */
	{ 0, 0, NULL, 0, NULL },
};

static const size_t typedesc_count =
	(sizeof(typedesc_table) / sizeof(typedesc_table[0])) - 1;

/*
 * Binary search for (type, rdclass) in the sorted table.
 * Returns the matching entry or NULL.
 */
static const dns_rdata_typedesc_t *
typedesc_find(dns_rdataclass_t rdclass, dns_rdatatype_t type) {
	size_t lo = 0;
	size_t hi = typedesc_count;

	while (lo < hi) {
		size_t mid = lo + (hi - lo) / 2;
		const dns_rdata_typedesc_t *td = &typedesc_table[mid];

		if (td->type < type ||
		    (td->type == type && td->rdclass < rdclass))
		{
			lo = mid + 1;
		} else if (td->type == type && td->rdclass == rdclass) {
			return td;
		} else {
			hi = mid;
		}
	}

	return NULL;
}

const dns_rdata_typedesc_t *
dns__rdata_typedesc_lookup(dns_rdataclass_t rdclass, dns_rdatatype_t type) {
	const dns_rdata_typedesc_t *td;

	/* Try exact (rdclass, type) match first */
	td = typedesc_find(rdclass, type);
	if (td != NULL) {
		return td;
	}

	/* Fall back to generic (rdclass=0) entry */
	if (rdclass != 0) {
		td = typedesc_find(0, type);
	}

	return td;
}

const dns_rdata_typedesc_t *
dns__rdata_typedesc_fromtext(const char *name, unsigned int length) {
	for (size_t i = 0; i < typedesc_count; i++) {
		const dns_rdata_typedesc_t *td = &typedesc_table[i];

		if (td->name == NULL) {
			continue;
		}

		if (strlen(td->name) == length &&
		    strncasecmp(td->name, name, length) == 0)
		{
			return td;
		}
	}

	return NULL;
}
