#!/bin/sh

# Copyright (C) Internet Systems Consortium, Inc. ("ISC")
#
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, you can obtain one at https://mozilla.org/MPL/2.0/.
#
# See the COPYRIGHT file distributed with this work for additional
# information regarding copyright ownership.

USAGE="# Usage: ${0} [-h] -s File.d [-o <File>]"

mode=
while getopts hGs:o: opt; do
  case "${opt}" in
    h) mode=header ;;
    s) input=$OPTARG ;;
    o) output=$OPTARG ;;
    \?)
      echo $USAGE
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

if test -z "${mode}" || test -z "${input}"; then
  echo $USAGE
  exit 1
fi

case "${mode}" in
  header)
    if test -z "${output}"; then
      output="$(basename "${input}" .d).h"
    fi
    awk '
    BEGIN {
        print "/* Generated by util/dtrace.sh shim (isc_log fallback for SDT probes). */"
        print "#pragma once"
        print ""
        print "#include <isc/log.h>"
        print ""
        print "#ifndef BIND9_DTRACE_LOG_LEVEL"
        print "#define BIND9_DTRACE_LOG_LEVEL ISC_LOG_DEBUG(99)"
        print "#endif"
        print ""
    }

    /^[[:space:]]*provider[[:space:]]/ {
        provider = $2
        gsub(/[{}; ]/, "", provider)
        next
    }

    /^[[:space:]]*probe[[:space:]]/ {
        line = $0
        sub(/^[[:space:]]*probe[[:space:]]+/, "", line)
        sub(/;[[:space:]]*$/, "", line)
        lp = index(line, "(")
        name = substr(line, 1, lp - 1)
        gsub(/[[:space:]]/, "", name)
        args_str = substr(line, lp + 1)
        sub(/\)[[:space:]]*$/, "", args_str)

        up_macro = toupper(provider) "_" toupper(name)

        n = 0
        macro_args = ""
        call_args = ""
        fmt = ""
        if (length(args_str) > 0) {
            n = split(args_str, argv, ",")
            for (i = 1; i <= n; i++) {
                t = argv[i]
                gsub(/^[[:space:]]+|[[:space:]]+$/, "", t)
                if (t == "int") {
                    spec = "%d"
                } else {
                    spec = "%p"
                }
                if (i > 1) {
                    fmt = fmt ", "
                    macro_args = macro_args ", "
                    call_args = call_args ", "
                }
                fmt = fmt spec
                macro_args = macro_args "a" i
                call_args = call_args "(a" i ")"
            }
        }

        printf "#define %s_ENABLED() isc_log_wouldlog(BIND9_DTRACE_LOG_LEVEL)\n", up_macro
        if (n == 0) {
            printf "#define %s() \\\n", up_macro
            printf "\tdo { \\\n"
            printf "\t\tif (isc_log_wouldlog(BIND9_DTRACE_LOG_LEVEL)) { \\\n"
            printf "\t\t\tisc_log_write(ISC_LOGCATEGORY_GENERAL, \\\n"
            printf "\t\t\t\tISC_LOGMODULE_OTHER, \\\n"
            printf "\t\t\t\tBIND9_DTRACE_LOG_LEVEL, \\\n"
            printf "\t\t\t\t\"%s:%s\"); \\\n", provider, name
            printf "\t\t} \\\n"
            printf "\t} while (0)\n"
        } else {
            printf "#define %s(%s) \\\n", up_macro, macro_args
            printf "\tdo { \\\n"
            printf "\t\tif (isc_log_wouldlog(BIND9_DTRACE_LOG_LEVEL)) { \\\n"
            printf "\t\t\tisc_log_write(ISC_LOGCATEGORY_GENERAL, \\\n"
            printf "\t\t\t\tISC_LOGMODULE_OTHER, \\\n"
            printf "\t\t\t\tBIND9_DTRACE_LOG_LEVEL, \\\n"
            printf "\t\t\t\t\"%s:%s(%s)\", %s); \\\n", provider, name, fmt, call_args
            printf "\t\t} \\\n"
            printf "\t} while (0)\n"
        }
        print ""
    }
    ' "${input}" >"${output}"
    ;;
esac
