/*
 * Copyright (C) Internet Systems Consortium, Inc. ("ISC")
 *
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See the COPYRIGHT file distributed with this work for additional
 * information regarding copyright ownership.
 */

#pragma once

/*! \file isccfg/clause.h
 * \brief
 * Interned clause names for cfg_clausedef_t.
 */

/* clang-format off */

#define CFG_CLAUSES \
    X(CFG_CLAUSE_6TO4_SELF, "6to4-self") \
    X(CFG_CLAUSE_ACACHE_CLEANING_INTERVAL, "acache-cleaning-interval") \
    X(CFG_CLAUSE_ACACHE_ENABLE, "acache-enable") \
    X(CFG_CLAUSE_ACL, "acl") \
    X(CFG_CLAUSE_ADDITIONAL_FROM_AUTH, "additional-from-auth") \
    X(CFG_CLAUSE_ADDITIONAL_FROM_CACHE, "additional-from-cache") \
    X(CFG_CLAUSE_ADDRESS, "address") \
    X(CFG_CLAUSE_ADDRESSES, "addresses") \
    X(CFG_CLAUSE_ADD_SOA, "add-soa") \
    X(CFG_CLAUSE_ADDZONECONF, "addzoneconf") \
    X(CFG_CLAUSE_ALGORITHM, "algorithm") \
    X(CFG_CLAUSE_ALGORITHMLIST, "algorithmlist") \
    X(CFG_CLAUSE_ALGORITHMS, "algorithms") \
    X(CFG_CLAUSE_ALL, "all") \
    X(CFG_CLAUSE_ALLOW, "allow") \
    X(CFG_CLAUSE_ALLOW_NEW_ZONES, "allow-new-zones") \
    X(CFG_CLAUSE_ALLOW_NOTIFY, "allow-notify") \
    X(CFG_CLAUSE_ALLOW_PROXY, "allow-proxy") \
    X(CFG_CLAUSE_ALLOW_PROXY_ON, "allow-proxy-on") \
    X(CFG_CLAUSE_ALLOW_QUERY, "allow-query") \
    X(CFG_CLAUSE_ALLOW_QUERY_CACHE, "allow-query-cache") \
    X(CFG_CLAUSE_ALLOW_QUERY_CACHE_ON, "allow-query-cache-on") \
    X(CFG_CLAUSE_ALLOW_QUERY_ON, "allow-query-on") \
    X(CFG_CLAUSE_ALLOW_RECURSION, "allow-recursion") \
    X(CFG_CLAUSE_ALLOW_RECURSION_ON, "allow-recursion-on") \
    X(CFG_CLAUSE_ALLOW_TRANSFER, "allow-transfer") \
    X(CFG_CLAUSE_ALLOW_UPDATE, "allow-update") \
    X(CFG_CLAUSE_ALLOW_UPDATE_FORWARDING, "allow-update-forwarding") \
    X(CFG_CLAUSE_ALLOW_V6_SYNTHESIS, "allow-v6-synthesis") \
    X(CFG_CLAUSE_ALL_PER_SECOND, "all-per-second") \
    X(CFG_CLAUSE_ALSO_NOTIFY, "also-notify") \
    X(CFG_CLAUSE_ALT_TRANSFER_SOURCE, "alt-transfer-source") \
    X(CFG_CLAUSE_ALT_TRANSFER_SOURCE_V6, "alt-transfer-source-v6") \
    X(CFG_CLAUSE_AML, "aml") \
    X(CFG_CLAUSE_ANCHORTYPE, "anchortype") \
    X(CFG_CLAUSE_ANSWER_COOKIE, "answer-cookie") \
    X(CFG_CLAUSE_ATTACH_CACHE, "attach-cache") \
    X(CFG_CLAUSE_AUTH_NXDOMAIN, "auth-nxdomain") \
    X(CFG_CLAUSE_AUTO, "auto") \
    X(CFG_CLAUSE_AUTO_DNSSEC, "auto-dnssec") \
    X(CFG_CLAUSE_AUTOMATIC_INTERFACE_SCAN, "automatic-interface-scan") \
    X(CFG_CLAUSE_AVOID_V4_UDP_PORTS, "avoid-v4-udp-ports") \
    X(CFG_CLAUSE_AVOID_V6_UDP_PORTS, "avoid-v6-udp-ports") \
    X(CFG_CLAUSE_BINDKEYS, "bindkeys") \
    X(CFG_CLAUSE_BINDKEYS_FILE, "bindkeys-file") \
    X(CFG_CLAUSE_BLACKHOLE, "blackhole") \
    X(CFG_CLAUSE_BLOCK_SIZE, "block-size") \
    X(CFG_CLAUSE_BLOCKSIZE, "blocksize") \
    X(CFG_CLAUSE_BOGUS, "bogus") \
    X(CFG_CLAUSE_BRACKETED_NETADDRLIST, "bracketed_netaddrlist") \
    X(CFG_CLAUSE_BREAK_DNSSEC, "break-dnssec") \
    X(CFG_CLAUSE_BUFFERED, "buffered") \
    X(CFG_CLAUSE_BUILTIN_TRUST_ANCHORS, "builtin-trust-anchors") \
    X(CFG_CLAUSE_CACHE_FILE, "cache-file") \
    X(CFG_CLAUSE_CA_FILE, "ca-file") \
    X(CFG_CLAUSE_CATALOG_ZONES, "catalog-zones") \
    X(CFG_CLAUSE_CATEGORY, "category") \
    X(CFG_CLAUSE_CDNSKEY, "cdnskey") \
    X(CFG_CLAUSE_CDS_DIGEST_TYPES, "cds-digest-types") \
    X(CFG_CLAUSE_CERT_FILE, "cert-file") \
    X(CFG_CLAUSE_CHANNEL, "channel") \
    X(CFG_CLAUSE_CHECKDS, "checkds") \
    X(CFG_CLAUSE_CHECK_DUP_RECORDS, "check-dup-records") \
    X(CFG_CLAUSE_CHECK_INTEGRITY, "check-integrity") \
    X(CFG_CLAUSE_CHECKMODE, "checkmode") \
    X(CFG_CLAUSE_CHECK_MX, "check-mx") \
    X(CFG_CLAUSE_CHECK_MX_CNAME, "check-mx-cname") \
    X(CFG_CLAUSE_CHECK_NAMES, "check-names") \
    X(CFG_CLAUSE_CHECKNAMES, "checknames") \
    X(CFG_CLAUSE_CHECK_SIBLING, "check-sibling") \
    X(CFG_CLAUSE_CHECK_SPF, "check-spf") \
    X(CFG_CLAUSE_CHECK_SRV_CNAME, "check-srv-cname") \
    X(CFG_CLAUSE_CHECK_SVCB, "check-svcb") \
    X(CFG_CLAUSE_CHECKTYPE, "checktype") \
    X(CFG_CLAUSE_CHECK_WILDCARD, "check-wildcard") \
    X(CFG_CLAUSE_CIPHERS, "ciphers") \
    X(CFG_CLAUSE_CIPHER_SUITES, "cipher-suites") \
    X(CFG_CLAUSE_CLASS, "class") \
    X(CFG_CLAUSE_CLEANING_INTERVAL, "cleaning-interval") \
    X(CFG_CLAUSE_CLIENTS, "clients") \
    X(CFG_CLAUSE_CLIENTS_PER_QUERY, "clients-per-query") \
    X(CFG_CLAUSE_CNAME, "cname") \
    X(CFG_CLAUSE_CONTROLS, "controls") \
    X(CFG_CLAUSE_COOKIEALG, "cookiealg") \
    X(CFG_CLAUSE_COOKIE_ALGORITHM, "cookie-algorithm") \
    X(CFG_CLAUSE_COOKIE_SECRET, "cookie-secret") \
    X(CFG_CLAUSE_CORESIZE, "coresize") \
    X(CFG_CLAUSE_CRITICAL, "critical") \
    X(CFG_CLAUSE_CSK, "csk") \
    X(CFG_CLAUSE_DATA, "data") \
    X(CFG_CLAUSE_DATABASE, "database") \
    X(CFG_CLAUSE_DATASIZE, "datasize") \
    X(CFG_CLAUSE_DATE, "date") \
    X(CFG_CLAUSE_DEALLOCATE_ON_EXIT, "deallocate-on-exit") \
    X(CFG_CLAUSE_DEBUG, "debug") \
    X(CFG_CLAUSE_DEBUGLEVEL, "debuglevel") \
    X(CFG_CLAUSE_DEFAULT, "default") \
    X(CFG_CLAUSE_DEFAULT_KEY, "default-key") \
    X(CFG_CLAUSE_DEFAULT_MASTERS, "default-masters") \
    X(CFG_CLAUSE_DEFAULT_PORT, "default-port") \
    X(CFG_CLAUSE_DEFAULT_PRIMARIES, "default-primaries") \
    X(CFG_CLAUSE_DEFAULT_SERVER, "default-server") \
    X(CFG_CLAUSE_DEFAULT_SOURCE_ADDRESS, "default-source-address") \
    X(CFG_CLAUSE_DEFAULT_SOURCE_ADDRESS_V6, "default-source-address-v6") \
    X(CFG_CLAUSE_DELEGATION_ONLY, "delegation-only") \
    X(CFG_CLAUSE_DELV, "delv") \
    X(CFG_CLAUSE_DENY, "deny") \
    X(CFG_CLAUSE_DENY_ANSWER_ADDRESSES, "deny-answer-addresses") \
    X(CFG_CLAUSE_DENY_ANSWER_ALIASES, "deny-answer-aliases") \
    X(CFG_CLAUSE_DESTINATIONLIST, "destinationlist") \
    X(CFG_CLAUSE_DESTINATIONS, "destinations") \
    X(CFG_CLAUSE_DHPARAM_FILE, "dhparam-file") \
    X(CFG_CLAUSE_DIALUP, "dialup") \
    X(CFG_CLAUSE_DIGESTS, "digests") \
    X(CFG_CLAUSE_DIRECTORY, "directory") \
    X(CFG_CLAUSE_DISABLE_ALGORITHMS, "disable-algorithms") \
    X(CFG_CLAUSE_DISABLED, "disabled") \
    X(CFG_CLAUSE_DISABLE_DS_DIGESTS, "disable-ds-digests") \
    X(CFG_CLAUSE_DISABLE_EMPTY_ZONE, "disable-empty-zone") \
    X(CFG_CLAUSE_DISCOUNT, "discount") \
    X(CFG_CLAUSE_DLZ, "dlz") \
    X(CFG_CLAUSE_DNS64, "dns64") \
    X(CFG_CLAUSE_DNS64_CONTACT, "dns64-contact") \
    X(CFG_CLAUSE_DNS64_SERVER, "dns64-server") \
    X(CFG_CLAUSE_DNSKEY_SIG_VALIDITY, "dnskey-sig-validity") \
    X(CFG_CLAUSE_DNSKEY_TTL, "dnskey-ttl") \
    X(CFG_CLAUSE_DNSRPS_ENABLE, "dnsrps-enable") \
    X(CFG_CLAUSE_DNSRPS_LIBRARY, "dnsrps-library") \
    X(CFG_CLAUSE_DNSRPS_OPTIONS, "dnsrps-options") \
    X(CFG_CLAUSE_DNSSEC_ACCEPT_EXPIRED, "dnssec-accept-expired") \
    X(CFG_CLAUSE_DNSSEC_DNSKEY_KSKONLY, "dnssec-dnskey-kskonly") \
    X(CFG_CLAUSE_DNSSEC_ENABLE, "dnssec-enable") \
    X(CFG_CLAUSE_DNSSECKEYS, "dnsseckeys") \
    X(CFG_CLAUSE_DNSSEC_LOADKEYS_INTERVAL, "dnssec-loadkeys-interval") \
    X(CFG_CLAUSE_DNSSEC_LOOKASIDE, "dnssec-lookaside") \
    X(CFG_CLAUSE_DNSSEC_MUST_BE_SECURE, "dnssec-must-be-secure") \
    X(CFG_CLAUSE_DNSSEC_POLICY, "dnssec-policy") \
    X(CFG_CLAUSE_DNSSEC_SECURE_TO_INSECURE, "dnssec-secure-to-insecure") \
    X(CFG_CLAUSE_DNSSEC_UPDATE_MODE, "dnssec-update-mode") \
    X(CFG_CLAUSE_DNSSEC_VALIDATION, "dnssec-validation") \
    X(CFG_CLAUSE_DNSTAP, "dnstap") \
    X(CFG_CLAUSE_DNSTAP_IDENTITY, "dnstap-identity") \
    X(CFG_CLAUSE_DNSTAP_OUTPUT, "dnstap-output") \
    X(CFG_CLAUSE_DNSTAPOUTPUT, "dnstapoutput") \
    X(CFG_CLAUSE_DNSTAP_TYPE, "dnstap_type") \
    X(CFG_CLAUSE_DNSTAP_VALUE, "dnstap_value") \
    X(CFG_CLAUSE_DNSTAP_VERSION, "dnstap-version") \
    X(CFG_CLAUSE_DOH, "doh") \
    X(CFG_CLAUSE_DROP, "drop") \
    X(CFG_CLAUSE_DSCP, "dscp") \
    X(CFG_CLAUSE_DSDIGESTLIST, "dsdigestlist") \
    X(CFG_CLAUSE_DTMODE, "dtmode") \
    X(CFG_CLAUSE_DUAL_STACK_SERVERS, "dual-stack-servers") \
    X(CFG_CLAUSE_DUMP_FILE, "dump-file") \
    X(CFG_CLAUSE_DYNDB, "dyndb") \
    X(CFG_CLAUSE_EDE, "ede") \
    X(CFG_CLAUSE_EDNS, "edns") \
    X(CFG_CLAUSE_EDNS_UDP_SIZE, "edns-udp-size") \
    X(CFG_CLAUSE_EDNS_VERSION, "edns-version") \
    X(CFG_CLAUSE_ELIGIBLE, "eligible") \
    X(CFG_CLAUSE_EMPTY_CONTACT, "empty-contact") \
    X(CFG_CLAUSE_EMPTY_SERVER, "empty-server") \
    X(CFG_CLAUSE_EMPTY_ZONES_ENABLE, "empty-zones-enable") \
    X(CFG_CLAUSE_ENDPOINTS, "endpoints") \
    X(CFG_CLAUSE_ERRORS_PER_SECOND, "errors-per-second") \
    X(CFG_CLAUSE_EXCEPT_FROM, "except-from") \
    X(CFG_CLAUSE_EXCLUDE, "exclude") \
    X(CFG_CLAUSE_EXEMPT_CLIENTS, "exempt-clients") \
    X(CFG_CLAUSE_EXPLICIT, "explicit") \
    X(CFG_CLAUSE_FAIL, "fail") \
    X(CFG_CLAUSE_FAKE_IQUERY, "fake-iquery") \
    X(CFG_CLAUSE_FETCHES, "fetches") \
    X(CFG_CLAUSE_FETCHESPER, "fetchesper") \
    X(CFG_CLAUSE_FETCHES_PER_SERVER, "fetches-per-server") \
    X(CFG_CLAUSE_FETCHES_PER_ZONE, "fetches-per-zone") \
    X(CFG_CLAUSE_FETCH_GLUE, "fetch-glue") \
    X(CFG_CLAUSE_FETCHQUOTA, "fetchquota") \
    X(CFG_CLAUSE_FETCH_QUOTA_PARAMS, "fetch-quota-params") \
    X(CFG_CLAUSE_FILE, "file") \
    X(CFG_CLAUSE_FILES, "files") \
    X(CFG_CLAUSE_FILTER_AAAA, "filter-aaaa") \
    X(CFG_CLAUSE_FILTER_AAAA_ON_V4, "filter-aaaa-on-v4") \
    X(CFG_CLAUSE_FILTER_AAAA_ON_V6, "filter-aaaa-on-v6") \
    X(CFG_CLAUSE_FIRST, "first") \
    X(CFG_CLAUSE_FLUSH_ZONES_ON_SHUTDOWN, "flush-zones-on-shutdown") \
    X(CFG_CLAUSE_FORWARD, "forward") \
    X(CFG_CLAUSE_FORWARDERS, "forwarders") \
    X(CFG_CLAUSE_FREQUENCY, "frequency") \
    X(CFG_CLAUSE_FSTRM_SET_BUFFER_HINT, "fstrm-set-buffer-hint") \
    X(CFG_CLAUSE_FSTRM_SET_FLUSH_TIMEOUT, "fstrm-set-flush-timeout") \
    X(CFG_CLAUSE_FSTRM_SET_INPUT_QUEUE_SIZE, "fstrm-set-input-queue-size") \
    X(CFG_CLAUSE_FSTRM_SET_OUTPUT_NOTIFY_THRESHOLD, "fstrm-set-output-notify-threshold") \
    X(CFG_CLAUSE_FSTRM_SET_OUTPUT_QUEUE_MODEL, "fstrm-set-output-queue-model") \
    X(CFG_CLAUSE_FSTRM_SET_OUTPUT_QUEUE_SIZE, "fstrm-set-output-queue-size") \
    X(CFG_CLAUSE_FSTRM_SET_REOPEN_INTERVAL, "fstrm-set-reopen-interval") \
    X(CFG_CLAUSE_FULL, "full") \
    X(CFG_CLAUSE_GEOIP_DIRECTORY, "geoip-directory") \
    X(CFG_CLAUSE_GEOIP_USE_ECS, "geoip-use-ecs") \
    X(CFG_CLAUSE_GLUE_CACHE, "glue-cache") \
    X(CFG_CLAUSE_GRANT, "grant") \
    X(CFG_CLAUSE_GROUP, "group") \
    X(CFG_CLAUSE_HAS_OLD_CLIENTS, "has-old-clients") \
    X(CFG_CLAUSE_HEARTBEAT_INTERVAL, "heartbeat-interval") \
    X(CFG_CLAUSE_HIGH, "high") \
    X(CFG_CLAUSE_HOSTNAME, "hostname") \
    X(CFG_CLAUSE_HOST_STATISTICS, "host-statistics") \
    X(CFG_CLAUSE_HOST_STATISTICS_MAX, "host-statistics-max") \
    X(CFG_CLAUSE_HTTP, "http") \
    X(CFG_CLAUSE_HTTP_LISTENER_CLIENTS, "http-listener-clients") \
    X(CFG_CLAUSE_HTTP_PORT, "http-port") \
    X(CFG_CLAUSE_HTTPS_PORT, "https-port") \
    X(CFG_CLAUSE_HTTP_STREAMS_PER_CONNECTION, "http-streams-per-connection") \
    X(CFG_CLAUSE_IDENTITY, "identity") \
    X(CFG_CLAUSE_INCREMENT, "increment") \
    X(CFG_CLAUSE_INET, "inet") \
    X(CFG_CLAUSE_INITIAL_FILE, "initial-file") \
    X(CFG_CLAUSE_INLINE_SIGNING, "inline-signing") \
    X(CFG_CLAUSE_IN_MEMORY, "in-memory") \
    X(CFG_CLAUSE_INTERFACE_INTERVAL, "interface-interval") \
    X(CFG_CLAUSE_IN_VIEW, "in-view") \
    X(CFG_CLAUSE_IPV4ONLY_CONTACT, "ipv4only-contact") \
    X(CFG_CLAUSE_IPV4ONLY_ENABLE, "ipv4only-enable") \
    X(CFG_CLAUSE_IPV4ONLY_SERVER, "ipv4only-server") \
    X(CFG_CLAUSE_IPV4_PREFIX_LENGTH, "ipv4-prefix-length") \
    X(CFG_CLAUSE_IPV6_PREFIX_LENGTH, "ipv6-prefix-length") \
    X(CFG_CLAUSE_ISO8601, "iso8601") \
    X(CFG_CLAUSE_ITERATIONS, "iterations") \
    X(CFG_CLAUSE_IXFR_BASE, "ixfr-base") \
    X(CFG_CLAUSE_IXFR_FROM_DIFFERENCES, "ixfr-from-differences") \
    X(CFG_CLAUSE_IXFR_RATIO, "ixfr_ratio") \
    X(CFG_CLAUSE_IXFR_TMP_FILE, "ixfr-tmp-file") \
    X(CFG_CLAUSE_JOURNAL, "journal") \
    X(CFG_CLAUSE_KASPKEY, "kaspkey") \
    X(CFG_CLAUSE_KASPKEYS, "kaspkeys") \
    X(CFG_CLAUSE_KEEP_RESPONSE_ORDER, "keep-response-order") \
    X(CFG_CLAUSE_KEY, "key") \
    X(CFG_CLAUSE_KEY_DIRECTORY, "key-directory") \
    X(CFG_CLAUSE_KEY_FILE, "key-file") \
    X(CFG_CLAUSE_KEYLIST, "keylist") \
    X(CFG_CLAUSE_KEYREF, "keyref") \
    X(CFG_CLAUSE_KEYS, "keys") \
    X(CFG_CLAUSE_KEYSTORAGE, "keystorage") \
    X(CFG_CLAUSE_KEY_STORE, "key-store") \
    X(CFG_CLAUSE_LAME_TTL, "lame-ttl") \
    X(CFG_CLAUSE_LENGTH, "length") \
    X(CFG_CLAUSE_LIBRARY, "library") \
    X(CFG_CLAUSE_LIFETIME, "lifetime") \
    X(CFG_CLAUSE_LISTENER_CLIENTS, "listener-clients") \
    X(CFG_CLAUSE_LISTEN_ON, "listen-on") \
    X(CFG_CLAUSE_LISTENON, "listenon") \
    X(CFG_CLAUSE_LISTEN_ON_V6, "listen-on-v6") \
    X(CFG_CLAUSE_LMDB_MAPSIZE, "lmdb-mapsize") \
    X(CFG_CLAUSE_LOCK_FILE, "lock-file") \
    X(CFG_CLAUSE_LOG, "log") \
    X(CFG_CLAUSE_LOG_FILE, "log_file") \
    X(CFG_CLAUSE_LOGGING, "logging") \
    X(CFG_CLAUSE_LOGLEVEL, "loglevel") \
    X(CFG_CLAUSE_LOG_ONLY, "log-only") \
    X(CFG_CLAUSE_LOG_REPORT_CHANNEL, "log-report-channel") \
    X(CFG_CLAUSE_LOG_SEVERITY, "log_severity") \
    X(CFG_CLAUSE_LOGSUFFIX, "logsuffix") \
    X(CFG_CLAUSE_LOW, "low") \
    X(CFG_CLAUSE_LWRES, "lwres") \
    X(CFG_CLAUSE_MAINTAIN, "maintain") \
    X(CFG_CLAUSE_MAINTAIN_IXFR_BASE, "maintain-ixfr-base") \
    X(CFG_CLAUSE_MANAGEDKEY, "managedkey") \
    X(CFG_CLAUSE_MANAGED_KEYS, "managed-keys") \
    X(CFG_CLAUSE_MANAGED_KEYS_DIRECTORY, "managed-keys-directory") \
    X(CFG_CLAUSE_MANUAL_MODE, "manual-mode") \
    X(CFG_CLAUSE_MANY_ANSWERS, "many-answers") \
    X(CFG_CLAUSE_MAPPED, "mapped") \
    X(CFG_CLAUSE_MASTERFILE_FORMAT, "masterfile-format") \
    X(CFG_CLAUSE_MASTERFILE_STYLE, "masterfile-style") \
    X(CFG_CLAUSE_MASTERS, "masters") \
    X(CFG_CLAUSE_MATCH_CLIENTS, "match-clients") \
    X(CFG_CLAUSE_MATCH_DESTINATIONS, "match-destinations") \
    X(CFG_CLAUSE_MATCH_MAPPED_ADDRESSES, "match-mapped-addresses") \
    X(CFG_CLAUSE_MATCH_RECURSIVE_ONLY, "match-recursive-only") \
    X(CFG_CLAUSE_MATCHTYPE, "matchtype") \
    X(CFG_CLAUSE_MAX_ACACHE_SIZE, "max-acache-size") \
    X(CFG_CLAUSE_MAX_CACHE_SIZE, "max-cache-size") \
    X(CFG_CLAUSE_MAX_CACHE_TTL, "max-cache-ttl") \
    X(CFG_CLAUSE_MAX_CLIENTS_PER_QUERY, "max-clients-per-query") \
    X(CFG_CLAUSE_MAX_DELEGATION_SERVERS, "max-delegation-servers") \
    X(CFG_CLAUSE_MAX_IXFR_LOG_SIZE, "max-ixfr-log-size") \
    X(CFG_CLAUSE_MAX_IXFR_RATIO, "max-ixfr-ratio") \
    X(CFG_CLAUSE_MAX_JOURNAL_SIZE, "max-journal-size") \
    X(CFG_CLAUSE_MAX_NCACHE_TTL, "max-ncache-ttl") \
    X(CFG_CLAUSE_MAX_POLICY_TTL, "max-policy-ttl") \
    X(CFG_CLAUSE_MAX_QUERY_COUNT, "max-query-count") \
    X(CFG_CLAUSE_MAX_QUERY_RESTARTS, "max-query-restarts") \
    X(CFG_CLAUSE_MAX_RECORDS, "max-records") \
    X(CFG_CLAUSE_MAX_RECORDS_PER_TYPE, "max-records-per-type") \
    X(CFG_CLAUSE_MAX_RECURSION_DEPTH, "max-recursion-depth") \
    X(CFG_CLAUSE_MAX_RECURSION_QUERIES, "max-recursion-queries") \
    X(CFG_CLAUSE_MAX_REFRESH_TIME, "max-refresh-time") \
    X(CFG_CLAUSE_MAX_RETRY_TIME, "max-retry-time") \
    X(CFG_CLAUSE_MAX_RSA_EXPONENT_SIZE, "max-rsa-exponent-size") \
    X(CFG_CLAUSE_MAX_STALE_TTL, "max-stale-ttl") \
    X(CFG_CLAUSE_MAX_TABLE_SIZE, "max-table-size") \
    X(CFG_CLAUSE_MAX_TRANSFER_IDLE_IN, "max-transfer-idle-in") \
    X(CFG_CLAUSE_MAX_TRANSFER_IDLE_OUT, "max-transfer-idle-out") \
    X(CFG_CLAUSE_MAX_TRANSFER_TIME_IN, "max-transfer-time-in") \
    X(CFG_CLAUSE_MAX_TRANSFER_TIME_OUT, "max-transfer-time-out") \
    X(CFG_CLAUSE_MAX_TYPES_PER_NAME, "max-types-per-name") \
    X(CFG_CLAUSE_MAX_UDP_SIZE, "max-udp-size") \
    X(CFG_CLAUSE_MAX_VALIDATION_FAILURES_PER_FETCH, "max-validation-failures-per-fetch") \
    X(CFG_CLAUSE_MAX_VALIDATIONS_PER_FETCH, "max-validations-per-fetch") \
    X(CFG_CLAUSE_MAX_ZONE_TTL, "max-zone-ttl") \
    X(CFG_CLAUSE_MEMSTATISTICS, "memstatistics") \
    X(CFG_CLAUSE_MEMSTATISTICS_FILE, "memstatistics-file") \
    X(CFG_CLAUSE_MESSAGE_COMPRESSION, "message-compression") \
    X(CFG_CLAUSE_MIN_CACHE_TTL, "min-cache-ttl") \
    X(CFG_CLAUSE_MINIMAL_ANY, "minimal-any") \
    X(CFG_CLAUSE_MINIMAL_RESPONSES, "minimal-responses") \
    X(CFG_CLAUSE_MIN_NCACHE_TTL, "min-ncache-ttl") \
    X(CFG_CLAUSE_MIN_NS_DOTS, "min-ns-dots") \
    X(CFG_CLAUSE_MIN_REFRESH_TIME, "min-refresh-time") \
    X(CFG_CLAUSE_MIN_RETRY_TIME, "min-retry-time") \
    X(CFG_CLAUSE_MIN_ROOTS, "min-roots") \
    X(CFG_CLAUSE_MIN_TABLE_SIZE, "min-table-size") \
    X(CFG_CLAUSE_MIN_TRANSFER_RATE_IN, "min-transfer-rate-in") \
    X(CFG_CLAUSE_MIN_UPDATE_INTERVAL, "min-update-interval") \
    X(CFG_CLAUSE_MODE, "mode") \
    X(CFG_CLAUSE_MPSC, "mpsc") \
    X(CFG_CLAUSE_MULTI_MASTER, "multi-master") \
    X(CFG_CLAUSE_MULTIPLE_CNAMES, "multiple-cnames") \
    X(CFG_CLAUSE_NAME, "name") \
    X(CFG_CLAUSE_NAMEDCONF, "namedconf") \
    X(CFG_CLAUSE_NAMED_XFER, "named-xfer") \
    X(CFG_CLAUSE_NAMELIST, "namelist") \
    X(CFG_CLAUSE_NAMEPORT, "nameport") \
    X(CFG_CLAUSE_NEW_ZONES_DIRECTORY, "new-zones-directory") \
    X(CFG_CLAUSE_NO_AUTH, "no-auth") \
    X(CFG_CLAUSE_NO_CASE_COMPRESS, "no-case-compress") \
    X(CFG_CLAUSE_NOCOOKIE_UDP_SIZE, "nocookie-udp-size") \
    X(CFG_CLAUSE_NODATA_PER_SECOND, "nodata-per-second") \
    X(CFG_CLAUSE_NONE, "none") \
    X(CFG_CLAUSE_NOSIT_UDP_SIZE, "nosit-udp-size") \
    X(CFG_CLAUSE_NOTIFY, "notify") \
    X(CFG_CLAUSE_NOTIFY_CFG, "notify-cfg") \
    X(CFG_CLAUSE_NOTIFY_DEFER, "notify-defer") \
    X(CFG_CLAUSE_NOTIFY_DELAY, "notify-delay") \
    X(CFG_CLAUSE_NOTIFY_RATE, "notify-rate") \
    X(CFG_CLAUSE_NOTIFY_SOURCE, "notify-source") \
    X(CFG_CLAUSE_NOTIFY_SOURCE_V6, "notify-source-v6") \
    X(CFG_CLAUSE_NOTIFY_TO_SOA, "notify-to-soa") \
    X(CFG_CLAUSE_NSDNAME_ENABLE, "nsdname-enable") \
    X(CFG_CLAUSE_NSDNAME_WAIT_RECURSE, "nsdname-wait-recurse") \
    X(CFG_CLAUSE_NSEC3PARAM, "nsec3param") \
    X(CFG_CLAUSE_NSEC3_TEST_ZONE, "nsec3-test-zone") \
    X(CFG_CLAUSE_NSIP_ENABLE, "nsip-enable") \
    X(CFG_CLAUSE_NSIP_WAIT_RECURSE, "nsip-wait-recurse") \
    X(CFG_CLAUSE_NTA_LIFETIME, "nta-lifetime") \
    X(CFG_CLAUSE_NTA_RECHECK, "nta-recheck") \
    X(CFG_CLAUSE_NULL, "null") \
    X(CFG_CLAUSE_NXDOMAIN_REDIRECT, "nxdomain-redirect") \
    X(CFG_CLAUSE_NXDOMAINS_PER_SECOND, "nxdomains-per-second") \
    X(CFG_CLAUSE_OFFLINE_KSK, "offline-ksk") \
    X(CFG_CLAUSE_OPTIONAL_CLASS, "optional_class") \
    X(CFG_CLAUSE_OPTIONAL_FACILITY, "optional_facility") \
    X(CFG_CLAUSE_OPTIONAL_UINT32, "optional_uint32") \
    X(CFG_CLAUSE_OPTIONS, "options") \
    X(CFG_CLAUSE_OPTOUT, "optout") \
    X(CFG_CLAUSE_ORDER, "order") \
    X(CFG_CLAUSE_ORDERING, "ordering") \
    X(CFG_CLAUSE_OWNER, "owner") \
    X(CFG_CLAUSE_PADDING, "padding") \
    X(CFG_CLAUSE_PARAMETERS, "parameters") \
    X(CFG_CLAUSE_PARENTAL_AGENTS, "parental-agents") \
    X(CFG_CLAUSE_PARENTAL_SOURCE, "parental-source") \
    X(CFG_CLAUSE_PARENTAL_SOURCE_V6, "parental-source-v6") \
    X(CFG_CLAUSE_PARENT_DS_TTL, "parent-ds-ttl") \
    X(CFG_CLAUSE_PARENT_PROPAGATION_DELAY, "parent-propagation-delay") \
    X(CFG_CLAUSE_PARENT_REGISTRATION_DELAY, "parent-registration-delay") \
    X(CFG_CLAUSE_PATH, "path") \
    X(CFG_CLAUSE_PERM, "perm") \
    X(CFG_CLAUSE_PID_FILE, "pid-file") \
    X(CFG_CLAUSE_PKCS11_URI, "pkcs11-uri") \
    X(CFG_CLAUSE_PLUGIN, "plugin") \
    X(CFG_CLAUSE_PLUGINTYPE, "plugintype") \
    X(CFG_CLAUSE_POLICY, "policy") \
    X(CFG_CLAUSE_POLICY_NAME, "policy name") \
    X(CFG_CLAUSE_POLICY_TUPLE, "policy tuple") \
    X(CFG_CLAUSE_PORT, "port") \
    X(CFG_CLAUSE_PORTIPLIST, "portiplist") \
    X(CFG_CLAUSE_PORT_TRANSPORT, "port-transport") \
    X(CFG_CLAUSE_PREFERRED_GLUE, "preferred-glue") \
    X(CFG_CLAUSE_PREFER_SERVER_CIPHERS, "prefer-server-ciphers") \
    X(CFG_CLAUSE_PREFETCH, "prefetch") \
    X(CFG_CLAUSE_PRIMARIES, "primaries") \
    X(CFG_CLAUSE_PRIMARY, "primary") \
    X(CFG_CLAUSE_PRINT_CATEGORY, "print-category") \
    X(CFG_CLAUSE_PRINT_SEVERITY, "print-severity") \
    X(CFG_CLAUSE_PRINT_TIME, "print-time") \
    X(CFG_CLAUSE_PRINTTIME, "printtime") \
    X(CFG_CLAUSE_PROTOCOLS, "protocols") \
    X(CFG_CLAUSE_PROVIDE_IXFR, "provide-ixfr") \
    X(CFG_CLAUSE_PROVIDE_ZONEVERSION, "provide-zoneversion") \
    X(CFG_CLAUSE_PROXY, "proxy") \
    X(CFG_CLAUSE_PUBKEY, "pubkey") \
    X(CFG_CLAUSE_PUBLISH_SAFETY, "publish-safety") \
    X(CFG_CLAUSE_PURGE_KEYS, "purge-keys") \
    X(CFG_CLAUSE_QMINMETHOD, "qminmethod") \
    X(CFG_CLAUSE_QNAME_MINIMIZATION, "qname-minimization") \
    X(CFG_CLAUSE_QNAME_WAIT_RECURSE, "qname-wait-recurse") \
    X(CFG_CLAUSE_QPS_SCALE, "qps-scale") \
    X(CFG_CLAUSE_QSTRINGORNONE, "qstringornone") \
    X(CFG_CLAUSE_QUERY, "query") \
    X(CFG_CLAUSE_QUERYLOG, "querylog") \
    X(CFG_CLAUSE_QUERYPORT_POOL_PORTS, "queryport-pool-ports") \
    X(CFG_CLAUSE_QUERYPORT_POOL_UPDATEINTERVAL, "queryport-pool-updateinterval") \
    X(CFG_CLAUSE_QUERY_SOURCE, "query-source") \
    X(CFG_CLAUSE_QUERYSOURCE, "querysource") \
    X(CFG_CLAUSE_QUERY_SOURCE_V6, "query-source-v6") \
    X(CFG_CLAUSE_RANDOM_DEVICE, "random-device") \
    X(CFG_CLAUSE_RATE_LIMIT, "rate-limit") \
    X(CFG_CLAUSE_RAW, "raw") \
    X(CFG_CLAUSE_RDATA1, "rdata1") \
    X(CFG_CLAUSE_RDATA2, "rdata2") \
    X(CFG_CLAUSE_RDATA3, "rdata3") \
    X(CFG_CLAUSE_READ_ONLY, "read-only") \
    X(CFG_CLAUSE_RECURSING_FILE, "recursing-file") \
    X(CFG_CLAUSE_RECURSION, "recursion") \
    X(CFG_CLAUSE_RECURSIVE_CLIENTS, "recursive-clients") \
    X(CFG_CLAUSE_RECURSIVE_ONLY, "recursive-only") \
    X(CFG_CLAUSE_REFERRALS_PER_SECOND, "referrals-per-second") \
    X(CFG_CLAUSE_REMOTE_HOSTNAME, "remote-hostname") \
    X(CFG_CLAUSE_REMOTES_ELEMENT, "remotes_element") \
    X(CFG_CLAUSE_REMOTESELEMENT, "remoteselement") \
    X(CFG_CLAUSE_REMOTE_SERVERS, "remote-servers") \
    X(CFG_CLAUSE_REQUEST_EXPIRE, "request-expire") \
    X(CFG_CLAUSE_REQUEST_IXFR, "request-ixfr") \
    X(CFG_CLAUSE_REQUEST_IXFR_MAX_DIFFS, "request-ixfr-max-diffs") \
    X(CFG_CLAUSE_REQUEST_NSID, "request-nsid") \
    X(CFG_CLAUSE_REQUEST_SIT, "request-sit") \
    X(CFG_CLAUSE_REQUEST_ZONEVERSION, "request-zoneversion") \
    X(CFG_CLAUSE_REQUIRE_COOKIE, "require-cookie") \
    X(CFG_CLAUSE_REQUIRE_SERVER_COOKIE, "require-server-cookie") \
    X(CFG_CLAUSE_RESERVED_SOCKETS, "reserved-sockets") \
    X(CFG_CLAUSE_RE_SIGN, "re-sign") \
    X(CFG_CLAUSE_RESOLVER_NONBACKOFF_TRIES, "resolver-nonbackoff-tries") \
    X(CFG_CLAUSE_RESOLVER_QUERY_TIMEOUT, "resolver-query-timeout") \
    X(CFG_CLAUSE_RESOLVER_RETRY_INTERVAL, "resolver-retry-interval") \
    X(CFG_CLAUSE_RESOLVER_USE_DNS64, "resolver-use-dns64") \
    X(CFG_CLAUSE_RESPONSE, "response") \
    X(CFG_CLAUSE_RESPONSELOG, "responselog") \
    X(CFG_CLAUSE_RESPONSE_PADDING, "response-padding") \
    X(CFG_CLAUSE_RESPONSE_POLICY, "response-policy") \
    X(CFG_CLAUSE_RESPONSES_PER_SECOND, "responses-per-second") \
    X(CFG_CLAUSE_RETIRE_SAFETY, "retire-safety") \
    X(CFG_CLAUSE_REUSEPORT, "reuseport") \
    X(CFG_CLAUSE_RFC2308_TYPE1, "rfc2308-type1") \
    X(CFG_CLAUSE_RNDCCONF, "rndcconf") \
    X(CFG_CLAUSE_RNDCKEY, "rndckey") \
    X(CFG_CLAUSE_ROLE, "role") \
    X(CFG_CLAUSE_ROOT_DELEGATION_ONLY, "root-delegation-only") \
    X(CFG_CLAUSE_ROOT_KEY_SENTINEL, "root-key-sentinel") \
    X(CFG_CLAUSE_RPZ, "rpz") \
    X(CFG_CLAUSE_RPZ_TUPLE, "rpz tuple") \
    X(CFG_CLAUSE_RRSET_ORDER, "rrset-order") \
    X(CFG_CLAUSE_RRSETORDER, "rrsetorder") \
    X(CFG_CLAUSE_SALT_LENGTH, "salt-length") \
    X(CFG_CLAUSE_SEARCH, "search") \
    X(CFG_CLAUSE_SECRET, "secret") \
    X(CFG_CLAUSE_SECROOTS_FILE, "secroots-file") \
    X(CFG_CLAUSE_SEND_COOKIE, "send-cookie") \
    X(CFG_CLAUSE_SEND_REPORT_CHANNEL, "send-report-channel") \
    X(CFG_CLAUSE_SERIAL_QUERIES, "serial-queries") \
    X(CFG_CLAUSE_SERIAL_QUERY_RATE, "serial-query-rate") \
    X(CFG_CLAUSE_SERIAL_UPDATE_METHOD, "serial-update-method") \
    X(CFG_CLAUSE_SERVER, "server") \
    X(CFG_CLAUSE_SERVER_ADDRESSES, "server-addresses") \
    X(CFG_CLAUSE_SERVER_ID, "server-id") \
    X(CFG_CLAUSE_SERVERID, "serverid") \
    X(CFG_CLAUSE_SERVER_LIST, "server-list") \
    X(CFG_CLAUSE_SERVER_NAMES, "server-names") \
    X(CFG_CLAUSE_SERVFAIL_TTL, "servfail-ttl") \
    X(CFG_CLAUSE_SERVFAIL_UNTIL_READY, "servfail-until-ready") \
    X(CFG_CLAUSE_SESSIONKEY, "sessionkey") \
    X(CFG_CLAUSE_SESSION_KEYALG, "session-keyalg") \
    X(CFG_CLAUSE_SESSION_KEYFILE, "session-keyfile") \
    X(CFG_CLAUSE_SESSION_KEYNAME, "session-keyname") \
    X(CFG_CLAUSE_SESSION_TICKETS, "session-tickets") \
    X(CFG_CLAUSE_SEVERITY, "severity") \
    X(CFG_CLAUSE_SIG0CHECKS_QUOTA, "sig0checks-quota") \
    X(CFG_CLAUSE_SIG0CHECKS_QUOTA_EXEMPT, "sig0checks-quota-exempt") \
    X(CFG_CLAUSE_SIG0KEY_CHECKS_LIMIT, "sig0key-checks-limit") \
    X(CFG_CLAUSE_SIG0MESSAGE_CHECKS_LIMIT, "sig0message-checks-limit") \
    X(CFG_CLAUSE_SIGNATURES_JITTER, "signatures-jitter") \
    X(CFG_CLAUSE_SIGNATURES_REFRESH, "signatures-refresh") \
    X(CFG_CLAUSE_SIGNATURES_VALIDITY, "signatures-validity") \
    X(CFG_CLAUSE_SIGNATURES_VALIDITY_DNSKEY, "signatures-validity-dnskey") \
    X(CFG_CLAUSE_SIG_SIGNING_NODES, "sig-signing-nodes") \
    X(CFG_CLAUSE_SIG_SIGNING_SIGNATURES, "sig-signing-signatures") \
    X(CFG_CLAUSE_SIG_SIGNING_TYPE, "sig-signing-type") \
    X(CFG_CLAUSE_SIG_VALIDITY_INTERVAL, "sig-validity-interval") \
    X(CFG_CLAUSE_SIPHASH24, "siphash24") \
    X(CFG_CLAUSE_SIT_SECRET, "sit-secret") \
    X(CFG_CLAUSE_SIZE, "size") \
    X(CFG_CLAUSE_SIZEVAL, "sizeval") \
    X(CFG_CLAUSE_SLIP, "slip") \
    X(CFG_CLAUSE_SOCKADDRNAMEPORT_ELEMENT, "sockaddrnameport_element") \
    X(CFG_CLAUSE_SORTLIST, "sortlist") \
    X(CFG_CLAUSE_SOURCE, "source") \
    X(CFG_CLAUSE_SOURCE_ADDRESS, "source-address") \
    X(CFG_CLAUSE_SOURCE_ADDRESS_V6, "source-address-v6") \
    X(CFG_CLAUSE_SOURCE_V6, "source-v6") \
    X(CFG_CLAUSE_STACKSIZE, "stacksize") \
    X(CFG_CLAUSE_STALE_ANSWER_CLIENT_TIMEOUT, "stale-answer-client-timeout") \
    X(CFG_CLAUSE_STALE_ANSWER_ENABLE, "stale-answer-enable") \
    X(CFG_CLAUSE_STALE_ANSWER_TTL, "stale-answer-ttl") \
    X(CFG_CLAUSE_STALE_CACHE_ENABLE, "stale-cache-enable") \
    X(CFG_CLAUSE_STALE_REFRESH_TIME, "stale-refresh-time") \
    X(CFG_CLAUSE_STARTUP_NOTIFY_RATE, "startup-notify-rate") \
    X(CFG_CLAUSE_STATIC_KEY, "static-key") \
    X(CFG_CLAUSE_STATISTICS_CHANNELS, "statistics-channels") \
    X(CFG_CLAUSE_STATISTICS_FILE, "statistics-file") \
    X(CFG_CLAUSE_STATISTICS_INTERVAL, "statistics-interval") \
    X(CFG_CLAUSE_STDERR, "stderr") \
    X(CFG_CLAUSE_STREAMS_PER_CONNECTION, "streams-per-connection") \
    X(CFG_CLAUSE_STRICT, "strict") \
    X(CFG_CLAUSE_SUFFIX, "suffix") \
    X(CFG_CLAUSE_SUPPORT_IXFR, "support-ixfr") \
    X(CFG_CLAUSE_SUPPRESS_INITIAL_NOTIFY, "suppress-initial-notify") \
    X(CFG_CLAUSE_SYNTH_FROM_DNSSEC, "synth-from-dnssec") \
    X(CFG_CLAUSE_SYSLOG, "syslog") \
    X(CFG_CLAUSE_TAG_MAX, "tag-max") \
    X(CFG_CLAUSE_TAG_MIN, "tag-min") \
    X(CFG_CLAUSE_TAG_RANGE, "tag-range") \
    X(CFG_CLAUSE_TAGRANGE, "tagrange") \
    X(CFG_CLAUSE_TCP_ADVERTISED_TIMEOUT, "tcp-advertised-timeout") \
    X(CFG_CLAUSE_TCP_CLIENTS, "tcp-clients") \
    X(CFG_CLAUSE_TCP_IDLE_TIMEOUT, "tcp-idle-timeout") \
    X(CFG_CLAUSE_TCP_INITIAL_TIMEOUT, "tcp-initial-timeout") \
    X(CFG_CLAUSE_TCP_KEEPALIVE, "tcp-keepalive") \
    X(CFG_CLAUSE_TCP_KEEPALIVE_TIMEOUT, "tcp-keepalive-timeout") \
    X(CFG_CLAUSE_TCP_LISTEN_QUEUE, "tcp-listen-queue") \
    X(CFG_CLAUSE_TCP_ONLY, "tcp-only") \
    X(CFG_CLAUSE_TCP_PRIMARIES_TIMEOUT, "tcp-primaries-timeout") \
    X(CFG_CLAUSE_TCP_RECEIVE_BUFFER, "tcp-receive-buffer") \
    X(CFG_CLAUSE_TCP_SEND_BUFFER, "tcp-send-buffer") \
    X(CFG_CLAUSE_TEMPLATE, "template") \
    X(CFG_CLAUSE_TIME_MINUTES, "time_minutes") \
    X(CFG_CLAUSE_TKEY_DHKEY, "tkey-dhkey") \
    X(CFG_CLAUSE_TKEY_DOMAIN, "tkey-domain") \
    X(CFG_CLAUSE_TKEY_GSSAPI_CREDENTIAL, "tkey-gssapi-credential") \
    X(CFG_CLAUSE_TKEY_GSSAPI_KEYTAB, "tkey-gssapi-keytab") \
    X(CFG_CLAUSE_TLS, "tls") \
    X(CFG_CLAUSE_TLSCONF, "tlsconf") \
    X(CFG_CLAUSE_TLS_PORT, "tls-port") \
    X(CFG_CLAUSE_TLS_PROTOCOLS, "tls_protocols") \
    X(CFG_CLAUSE_TOPOLOGY, "topology") \
    X(CFG_CLAUSE_TRAFFIC_BYTES, "traffic_bytes") \
    X(CFG_CLAUSE_TRANSFER_FORMAT, "transfer-format") \
    X(CFG_CLAUSE_TRANSFER_MESSAGE_SIZE, "transfer-message-size") \
    X(CFG_CLAUSE_TRANSFERS, "transfers") \
    X(CFG_CLAUSE_TRANSFERS_IN, "transfers-in") \
    X(CFG_CLAUSE_TRANSFER_SOURCE, "transfer-source") \
    X(CFG_CLAUSE_TRANSFER_SOURCE_V6, "transfer-source-v6") \
    X(CFG_CLAUSE_TRANSFERS_OUT, "transfers-out") \
    X(CFG_CLAUSE_TRANSFERS_PER_NS, "transfers-per-ns") \
    X(CFG_CLAUSE_TRANSPORT, "transport") \
    X(CFG_CLAUSE_TREAT_CR_AS_SPACE, "treat-cr-as-space") \
    X(CFG_CLAUSE_TRIGGER, "trigger") \
    X(CFG_CLAUSE_TRUST_ANCHORS, "trust-anchors") \
    X(CFG_CLAUSE_TRUST_ANCHOR_TELEMETRY, "trust-anchor-telemetry") \
    X(CFG_CLAUSE_TRUSTED_KEYS, "trusted-keys") \
    X(CFG_CLAUSE_TRY_TCP_REFRESH, "try-tcp-refresh") \
    X(CFG_CLAUSE_TUPLE, "tuple") \
    X(CFG_CLAUSE_TYPE, "type") \
    X(CFG_CLAUSE_TYPES, "types") \
    X(CFG_CLAUSE_UDP_RECEIVE_BUFFER, "udp-receive-buffer") \
    X(CFG_CLAUSE_UDP_SEND_BUFFER, "udp-send-buffer") \
    X(CFG_CLAUSE_UNIX, "unix") \
    X(CFG_CLAUSE_UNLIMITED, "unlimited") \
    X(CFG_CLAUSE_UPDATE_CHECK_KSK, "update-check-ksk") \
    X(CFG_CLAUSE_UPDATE_POLICY, "update-policy") \
    X(CFG_CLAUSE_UPDATE_QUOTA, "update-quota") \
    X(CFG_CLAUSE_USE_ALT_TRANSFER_SOURCE, "use-alt-transfer-source") \
    X(CFG_CLAUSE_USE_ID_POOL, "use-id-pool") \
    X(CFG_CLAUSE_USE_IXFR, "use-ixfr") \
    X(CFG_CLAUSE_USE_QUERYPORT_POOL, "use-queryport-pool") \
    X(CFG_CLAUSE_USE_V4_UDP_PORTS, "use-v4-udp-ports") \
    X(CFG_CLAUSE_USE_V6_UDP_PORTS, "use-v6-udp-ports") \
    X(CFG_CLAUSE_V6_BIAS, "v6-bias") \
    X(CFG_CLAUSE_VALIDATE_EXCEPT, "validate-except") \
    X(CFG_CLAUSE_VALIDITY, "validity") \
    X(CFG_CLAUSE_VALUE, "value") \
    X(CFG_CLAUSE_VERSION, "version") \
    X(CFG_CLAUSE_VERSIONS, "versions") \
    X(CFG_CLAUSE_VIEW, "view") \
    X(CFG_CLAUSE_WARN, "warn") \
    X(CFG_CLAUSE_WINDOW, "window") \
    X(CFG_CLAUSE_ZERO_NO_SOA_TTL, "zero-no-soa-ttl") \
    X(CFG_CLAUSE_ZERO_NO_SOA_TTL_CACHE, "zero-no-soa-ttl-cache") \
    X(CFG_CLAUSE_ZONE, "zone") \
    X(CFG_CLAUSE_ZONE_DIRECTORY, "zone-directory") \
    X(CFG_CLAUSE_ZONE_LIST, "zone list") \
    X(CFG_CLAUSE_ZONE_NAME, "zone name") \
    X(CFG_CLAUSE_ZONEOPTS, "zoneopts") \
    X(CFG_CLAUSE_ZONE_PROPAGATION_DELAY, "zone-propagation-delay") \
    X(CFG_CLAUSE_ZONESTAT, "zonestat") \
    X(CFG_CLAUSE_ZONE_STATISTICS, "zone-statistics") \
    X(CFG_CLAUSE_ZONETYPE, "zonetype") \

/* clang-format on */

enum cfg_clause {
	CFG_CLAUSE__NONE = 0,
#define X(name, str) name,
	CFG_CLAUSES
#undef X
	CFG_CLAUSE__COUNT
};

extern const char *cfg_clause_as_string[];
